# Generated by Django 4.2.27 on 2026-01-29 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Industry Name')),
                ('type', models.CharField(max_length=120)),
                ('state', models.CharField(max_length=180, null=True, verbose_name='State')),
                ('city', models.CharField(max_length=180, null=True, verbose_name='City')),
                ('address', models.TextField(blank=True, default=None, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='River',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='River Name')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240, verbose_name='Site Name')),
                ('prefix', models.CharField(max_length=120, unique=True, verbose_name='Site Prefix')),
                ('state', models.CharField(max_length=180, null=True, verbose_name='State')),
                ('city', models.CharField(max_length=180, null=True, verbose_name='City')),
                ('address', models.TextField(blank=True, default=None, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True)),
                ('status', models.CharField(choices=[('Live', 'Live'), ('Offline', 'Offline'), ('Delay', 'Delay')], default='Offline', max_length=10)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corepy.industry', verbose_name='Industry')),
                ('river', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corepy.river', verbose_name='River')),
            ],
        ),
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='corepy.site')),
                ('last_seen', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data Received Time')),
                ('reading', models.JSONField()),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='Data Read Time')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default=None, max_length=120, null=True, unique=True)),
                ('name', models.CharField(max_length=240, verbose_name='User Name')),
                ('phone', models.CharField(max_length=10, verbose_name='User Phone')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('Industry', 'Industry'), ('Admin', 'Admin'), ('Staff', 'Staff')], max_length=20)),
                ('permissions', models.ManyToManyField(default=None, to='auth.permission')),
                ('site', models.ManyToManyField(default=None, to='corepy.site')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='industry',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corepy.userprofile'),
        ),
        migrations.CreateModel(
            name='Readings',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('reading', models.JSONField()),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corepy.site')),
            ],
            options={
                'unique_together': {('timestamp', 'site')},
            },
        ),
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('min', models.FloatField(default=0)),
                ('max', models.FloatField(default=0)),
                ('unit', models.CharField(blank=True, max_length=8, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='corepy.site')),
            ],
            options={
                'unique_together': {('site', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ExceedanceReports',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('min', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max', models.DecimalField(decimal_places=2, max_digits=5)),
                ('parameter', models.CharField(max_length=16)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Parameter Value')),
                ('timestamp', models.DateTimeField(verbose_name='reading time')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='received time')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corepy.site', verbose_name='Site')),
            ],
            options={
                'verbose_name': 'Exceedance',
                'verbose_name_plural': 'Exceedances',
                'indexes': [models.Index(fields=['site', 'timestamp'], name='corepy_exce_site_id_0fc14a_idx')],
                'unique_together': {('site', 'timestamp', 'parameter')},
            },
        ),
    ]
