# Generated by Django 4.2.27 on 2026-05-27 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corepy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readings',
            name='reading',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='last_seen',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='reading',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='timestamp',
            field=models.DateTimeField(db_index=True),
        ),
    ]
